services:
  - type: web
    name: alabina-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
databases:
  - name: alabina-db
    databaseName: ecommerce
    user: alabina